"""Tests for what an acoustic-only estimator can and cannot tell apart (experiment 06).

These functions take arrays. Building the twin *world* is a generator concern
(``generator.affine_twin_world``); deciding whether the two are distinguishable from
observations is an inference concern and lives here.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from analysis.metrics import NON_IDENTIFIABLE, best_linear_map_error, relative_error

__all__ = [
    "TwoSampleResult",
    "permutation_test_mean_trajectory",
    "state_matrix",
    "spectral_invariants",
    "spectral_gap",
    "latent_gap_report",
]


@dataclass
class TwoSampleResult:
    statistic: float
    p_value: float
    n_perm: int
    null_quantile_95: float

    @property
    def distinguishable(self) -> bool:
        return self.p_value < 0.05


def permutation_test_mean_trajectory(
    A: np.ndarray, B: np.ndarray, n_perm: int = 500, seed: int = 0
) -> TwoSampleResult:
    """Permutation test on the largest per-frame mean difference between two corpora.

    ``A`` and ``B`` are (n, T, d) observed trajectories. The statistic is
    ``max_t ||mean_A(t) - mean_B(t)||``; the null is generated by shuffling the corpus
    label across segments, which is exactly the exchangeability that holds if the two
    worlds are observationally identical.
    """
    rng = np.random.default_rng(seed)
    A, B = np.asarray(A, float), np.asarray(B, float)
    nA = A.shape[0]
    pooled = np.concatenate([A, B], axis=0)

    def stat(idx_a, idx_b):
        return float(np.max(np.linalg.norm(pooled[idx_a].mean(0) - pooled[idx_b].mean(0), axis=-1)))

    obs = stat(np.arange(nA), np.arange(nA, pooled.shape[0]))
    null = np.empty(n_perm)
    for i in range(n_perm):
        perm = rng.permutation(pooled.shape[0])
        null[i] = stat(perm[:nA], perm[nA:])
    p = float((1.0 + np.sum(null >= obs)) / (1.0 + n_perm))
    return TwoSampleResult(
        statistic=obs, p_value=p, n_perm=n_perm, null_quantile_95=float(np.quantile(null, 0.95))
    )


def state_matrix(A_u: np.ndarray, A_v: np.ndarray) -> np.ndarray:
    """Assemble [[0, I], [A_u, A_v]] from an acceleration law."""
    d = A_u.shape[0]
    A = np.zeros((2 * d, 2 * d))
    A[:d, d:] = np.eye(d)
    A[d:, :d] = A_u
    A[d:, d:] = A_v
    return A


def spectral_invariants(A_u: np.ndarray, A_v: np.ndarray) -> np.ndarray:
    """Eigenvalues of the state matrix, sorted -- invariant under any change of basis.

    This is the quantity Hypothesis 2 predicts *is* recoverable: a latent relabelling
    conjugates the state matrix, and conjugation preserves the spectrum. Latent
    coordinates are not identifiable; the poles of the observable dynamics are.
    """
    ev = np.linalg.eigvals(state_matrix(np.asarray(A_u, float), np.asarray(A_v, float)))
    return ev[np.lexsort((ev.imag, ev.real))]


def spectral_gap(a_u1, a_v1, a_u2, a_v2) -> float:
    """Relative difference between two systems' spectra."""
    e1, e2 = spectral_invariants(a_u1, a_v1), spectral_invariants(a_u2, a_v2)
    denom = np.linalg.norm(e1)
    return float(np.linalg.norm(e1 - e2) / denom) if denom > 0 else float("nan")


@dataclass
class LatentGapReport:
    """How different two latent parameterisations are, and how similar their observables."""

    latent_relative_gap: float
    affine_reparam_residual: float
    observable_gap: float
    spectral_gap: float
    verdict: str


def latent_gap_report(
    latent_1: np.ndarray,
    latent_2: np.ndarray,
    observable_1: np.ndarray,
    observable_2: np.ndarray,
    spectral: float,
    tol: float = 1e-6,
) -> LatentGapReport:
    """Summarise a twin pair: latents far apart, observables identical => NON-IDENTIFIABLE.

    ``affine_reparam_residual`` is the residual after the best affine map from latent 1
    to latent 2. Near zero means the two latents are the *same object in different
    coordinates* -- which is the equivalence class the framework should be claiming,
    rather than the coordinates themselves.
    """
    lat_gap = relative_error(latent_2, latent_1)
    reparam, _ = best_linear_map_error(
        np.asarray(latent_1, float).reshape(-1, np.shape(latent_1)[-1]),
        np.asarray(latent_2, float).reshape(-1, np.shape(latent_2)[-1]),
    )
    obs_gap = float(np.max(np.abs(np.asarray(observable_1) - np.asarray(observable_2))))
    return LatentGapReport(
        latent_relative_gap=lat_gap,
        affine_reparam_residual=reparam,
        observable_gap=obs_gap,
        spectral_gap=spectral,
        verdict=NON_IDENTIFIABLE if obs_gap < tol and lat_gap > tol else "SEPARABLE",
    )
