"""Self-test for the visual-baseline provenance guard (#611).

Drives BOTH directions: the guard must fire when a baseline changes without a
recorded reason, and must stay silent otherwise. A guard only tested in the
passing direction is how `check-js-workspace-hygiene` shipped inverted (#702).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MODULE_PATH = REPO_ROOT / "scripts" / "check_visual_baseline_provenance.py"

spec = importlib.util.spec_from_file_location("check_visual_baseline_provenance", MODULE_PATH)
assert spec and spec.loader
guard = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = guard
spec.loader.exec_module(guard)

SNAPS = "legal-search/frontend/e2e/visual.spec.ts-snapshots"
PROVENANCE = f"{SNAPS}/PROVENANCE.md"

GOOD_ENTRY = """# Visual baseline provenance

## 2026-07-19 — PR #999 — refresh

- Generated by: CI on ubuntu-latest
- Reason: the app intentionally changed the header; new image is correct.
- Files:
  - app-header-linux.png
"""


def test_passes_when_no_baseline_changed():
    changed = ["legal-search/frontend/src/app/page.tsx", "README.md"]
    assert guard.evaluate(changed, "") == []


def test_fails_when_baseline_changed_without_provenance():
    changed = [f"{SNAPS}/app-header-linux.png"]
    errors = guard.evaluate(changed, "")
    assert errors, "guard must fire on an unrecorded baseline bless"
    assert any("PROVENANCE.md was not updated" in e for e in errors)


def test_fails_when_provenance_touched_but_file_not_named():
    changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
    # Ledger updated, but for a different image.
    text = GOOD_ENTRY.replace("app-header-linux.png", "workspace-mobile-linux.png")
    errors = guard.evaluate(changed, text)
    assert any("app-header-linux.png" in e and "not named" in e for e in errors)


def test_fails_when_newest_entry_has_no_reason():
    changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
    text = """# Visual baseline provenance

## 2026-07-19 — PR #999 — refresh

- Files:
  - app-header-linux.png
"""
    errors = guard.evaluate(changed, text)
    assert any("missing required field" in e for e in errors)


def test_passes_with_a_complete_entry():
    changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
    assert guard.evaluate(changed, GOOD_ENTRY) == []


def test_deleted_baseline_also_requires_a_reason():
    """Removing coverage is a change to what is asserted, so it is recorded too."""
    changed = [f"{SNAPS}/retired-shot-linux.png"]
    assert guard.evaluate(changed, "") != []


def test_ignores_non_png_files_in_the_snapshot_dir():
    changed = [PROVENANCE]
    assert guard.evaluate(changed, GOOD_ENTRY) == []


def test_real_repo_ledger_satisfies_its_own_required_fields():
    """The committed ledger must itself pass the shape the guard demands."""
    text = (REPO_ROOT / PROVENANCE).read_text(encoding="utf-8")
    newest = guard._newest_entry(text)
    assert newest is not None, "ledger has no entries"
    for field in guard.REQUIRED_ENTRY_FIELDS:
        assert field in newest, f"committed ledger's newest entry lacks {field}"
