"""Self-test for the visual-baseline provenance guard (#611).

Drives BOTH directions: the guard must fire when a baseline changes without a
recorded reason, and must stay silent otherwise. A guard only tested in the
passing direction is how `check-js-workspace-hygiene` shipped inverted (#702).

WHY THIS IS A `TestCase` AND NOT BARE `test_*` FUNCTIONS
--------------------------------------------------------
CI runs ``python -m unittest discover -s scripts/tests -p "test_*.py"``
(`.github/workflows/docs-and-contracts.yml`), and `unittest` collects **only**
`TestCase` subclasses. Written as module-level functions, every assertion in this
file passed under a local pytest and executed *nowhere* in CI — the guard against
silently blessed baselines was itself silently unrun. That is #685's shape
("tests that run nowhere"), one directory over.

Keep this a `TestCase`. `check_test_reachability.py` will not catch a regression
here: the file *is* under a gated path, it simply cannot be collected.
"""

from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MODULE_PATH = REPO_ROOT / "scripts" / "check_visual_baseline_provenance.py"

spec = importlib.util.spec_from_file_location("check_visual_baseline_provenance", MODULE_PATH)
assert spec and spec.loader
guard = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = guard
spec.loader.exec_module(guard)

SNAPS = "legal-search/frontend/e2e/visual.spec.ts-snapshots"
PROVENANCE = f"{SNAPS}/PROVENANCE.md"

GOOD_ENTRY = """# Visual baseline provenance

## 2026-07-19 — PR #999 — refresh

- Generated by: CI on ubuntu-latest
- Reason: the app intentionally changed the header; new image is correct.
- Files:
  - app-header-linux.png
"""

# Verbatim shape of what `visual-baseline-refresh` commits before a human edits it.
PLACEHOLDER_ENTRY = """# Visual baseline provenance

## 2026-07-28 — PR #819 — CI-generated refresh

- Generated by: `visual-baseline-refresh` on `ubuntu-latest` ([run](https://example/1))
- Requested by: @someone
- Reason: _requested via the `visual-baseline-refresh` label._
  **Replace this line with why the NEW image is correct before merging.**
  A reviewer must be able to check the claim against the diff.
- Files:
  - app-header-linux.png
"""


class VisualBaselineProvenanceGuardTests(unittest.TestCase):
    def test_passes_when_no_baseline_changed(self) -> None:
        changed = ["legal-search/frontend/src/app/page.tsx", "README.md"]
        self.assertEqual(guard.evaluate(changed, ""), [])

    def test_fails_when_baseline_changed_without_provenance(self) -> None:
        changed = [f"{SNAPS}/app-header-linux.png"]
        errors = guard.evaluate(changed, "")
        self.assertTrue(errors, "guard must fire on an unrecorded baseline bless")
        self.assertTrue(any("PROVENANCE.md was not updated" in e for e in errors))

    def test_fails_when_provenance_touched_but_file_not_named(self) -> None:
        changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
        # Ledger updated, but for a different image.
        text = GOOD_ENTRY.replace("app-header-linux.png", "workspace-mobile-linux.png")
        errors = guard.evaluate(changed, text)
        self.assertTrue(any("app-header-linux.png" in e and "not named" in e for e in errors))

    def test_fails_when_newest_entry_has_no_reason(self) -> None:
        changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
        text = """# Visual baseline provenance

## 2026-07-19 — PR #999 — refresh

- Files:
  - app-header-linux.png
"""
        errors = guard.evaluate(changed, text)
        self.assertTrue(any("missing required field" in e for e in errors))

    def test_passes_with_a_complete_entry(self) -> None:
        changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
        self.assertEqual(guard.evaluate(changed, GOOD_ENTRY), [])

    def test_deleted_baseline_also_requires_a_reason(self) -> None:
        """Removing coverage is a change to what is asserted, so it is recorded too."""
        changed = [f"{SNAPS}/retired-shot-linux.png"]
        self.assertNotEqual(guard.evaluate(changed, ""), [])

    def test_ignores_non_png_files_in_the_snapshot_dir(self) -> None:
        changed = [PROVENANCE]
        self.assertEqual(guard.evaluate(changed, GOOD_ENTRY), [])

    def test_real_repo_ledger_satisfies_its_own_required_fields(self) -> None:
        """The committed ledger must itself pass the shape the guard demands."""
        text = (REPO_ROOT / PROVENANCE).read_text(encoding="utf-8")
        newest = guard._newest_entry(text)
        self.assertIsNotNone(newest, "ledger has no entries")
        for field in guard.REQUIRED_ENTRY_FIELDS:
            self.assertIn(field, newest, f"committed ledger's newest entry lacks {field}")

    # ------------------------------------------------------------------
    # The placeholder rule (#819)
    # ------------------------------------------------------------------

    def test_fails_when_the_refresh_placeholder_survives(self) -> None:
        """The refresh job's own commit must not go green.

        CI can record who regenerated a baseline and which files moved; only a human
        can say why the NEW image is correct. A `Reason:` satisfied by the placeholder
        is how the ledger goes decorative — three entries reached `main` that way
        (#791, #717 x2), so for those baselines the claim a reviewer is meant to check
        was never made.
        """
        changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
        errors = guard.evaluate(changed, PLACEHOLDER_ENTRY)
        self.assertTrue(errors, "guard must fire on an unfilled placeholder reason")
        self.assertTrue(any("placeholder reason" in e for e in errors))

    def test_placeholder_in_an_older_entry_does_not_block_a_new_refresh(self) -> None:
        """Only the newest stanza is judged.

        The historical unfilled entries are not honestly fixable — nobody can
        reconstruct why an image they did not generate was correct — so they must not
        wedge every future baseline change.
        """
        text = GOOD_ENTRY + "\n" + PLACEHOLDER_ENTRY.split("\n", 1)[1]
        changed = [f"{SNAPS}/app-header-linux.png", PROVENANCE]
        self.assertEqual(guard.evaluate(changed, text), [])

    def test_placeholder_is_ignored_when_no_baseline_changed(self) -> None:
        """A PR that touches no baseline must not be blocked by a ledger it did not write."""
        self.assertEqual(guard.evaluate(["README.md"], PLACEHOLDER_ENTRY), [])

    def test_real_repo_ledger_has_no_unfilled_placeholder_in_its_newest_entry(self) -> None:
        text = (REPO_ROOT / PROVENANCE).read_text(encoding="utf-8")
        newest = guard._newest_entry(text)
        self.assertIsNotNone(newest)
        for marker in guard.PLACEHOLDER_MARKERS:
            self.assertNotIn(
                marker,
                newest,
                "the committed ledger's newest entry still carries the refresh placeholder",
            )


if __name__ == "__main__":
    unittest.main()
