#!/usr/bin/env python3
"""Refuse a visual baseline captured from a base that no longer exists.

The failure this exists for, observed 2026-09-20
------------------------------------------------
PR #1054 moved the admin Playwright suite onto a production build, which removed
Next.js's dev-mode indicator from ``run-detail-v2-chromium-linux.png`` and
committed the corrected baseline to ``main``.

PR #1051 had been branched earlier and carried a baseline of the SAME file,
regenerated by the ``visual-baseline-refresh`` job from its own base — a base
that predates #1054. That image therefore still contained the dev indicator.

Merging it would have reverted #1054's correction, and **nothing in CI would
have said so**:

- ``admin-visual-regression`` compares the run against the baseline *in the same
  tree*, so a reverted baseline matches the reverted code and passes.
- ``check_visual_baseline_provenance`` asks whether a ledger entry exists and
  names the file. It does — the refresh job wrote one. The entry is truthful
  about who captured the image and when; it simply captured the wrong thing.
- A human reading the diff sees ``Bin 737887 -> 738352 bytes``. Nothing in that
  tells you which of two competing corrections you are keeping.

The git conflict only appears if both branches touch the file before either
merges. Once the first one lands, the second rebases cleanly — the bytes are
replaced wholesale — and the regression is silent.

What this guard asserts
-----------------------
For every baseline this branch changed: the base branch must not have changed
that same file since this branch forked. If it has, the branch's capture is of
an older world and must be regenerated on the current one.

It does NOT ask whether the image is *correct*; ``check_visual_baseline_
provenance.py`` owns the claim, and only a human can make it. This asks the
narrower question a machine can answer: was it taken from the base everyone else
is now standing on?

Why not just require branches to be up to date
----------------------------------------------
Because that would fire on every PR, and a rule that fires on PRs it has nothing
to say about is a rule people learn to bypass. This fires only when the base has
moved *the very file the branch is replacing* — which is exactly the collision
#913 documented (a PNG has no merge strategy) and nothing else.

Outcomes
--------
``0``  no baseline changed, or every changed baseline forked from the base's
       current version.
``1``  at least one baseline was captured from a superseded base.
``2``  DID-NOT-RUN — no git, no base ref, or a shallow clone with no merge base.
       A guard whose prerequisites are absent has not passed (AGENTS.md).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# The surfaces that own pixel baselines. Kept in step with
# `check_visual_baseline_provenance.py`; `test_snapshot_dirs_match_the_provenance_guard`
# fails if the two drift, because a directory guarded by one and not the other is
# the gap both were written to close.
SNAPSHOT_DIRS: tuple[Path, ...] = (
    Path("legal-search/frontend/e2e/visual.spec.ts-snapshots"),
    Path("platform-control/admin/e2e/visual.spec.ts-snapshots"),
)

BASELINE_SUFFIXES = (".png",)

DID_NOT_RUN = 2


class GitUnavailable(RuntimeError):
    """Raised when the repository cannot answer the question at all."""


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise GitUnavailable(f"git {' '.join(args)}: {result.stderr.strip()}")
    return result.stdout.strip()


def _blob_at(repo: Path, rev: str, path: str) -> str | None:
    """The blob id of ``path`` at ``rev``, or None when it does not exist there."""
    try:
        return _git(repo, "rev-parse", f"{rev}:{path}")
    except GitUnavailable:
        return None


def changed_baselines(repo: Path, merge_base: str, head: str) -> list[str]:
    raw = _git(repo, "diff", "--name-only", f"{merge_base}..{head}", "--", *[d.as_posix() for d in SNAPSHOT_DIRS])
    return [
        line
        for line in raw.splitlines()
        if line.strip() and line.endswith(BASELINE_SUFFIXES)
    ]


def superseded_baselines(repo: Path, base: str, head: str) -> list[str]:
    """Baselines this branch changed that the base has also moved since the fork.

    A file the branch changed is stale when the base's current blob differs from
    the blob the branch forked from. Both "the base changed it" and "the base
    deleted it" count; a file that exists on neither side cannot be stale.
    """
    merge_base = _git(repo, "merge-base", head, base)
    stale: list[str] = []
    for path in changed_baselines(repo, merge_base, head):
        at_fork = _blob_at(repo, merge_base, path)
        at_base = _blob_at(repo, base, path)
        if at_fork is None:
            # Added on this branch. The base cannot have superseded a file this
            # branch introduced.
            continue
        if at_fork != at_base:
            stale.append(path)
    return sorted(stale)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="check_baseline_stale_base",
        description=(
            "Refuse a visual baseline captured from a base the branch has since "
            "fallen behind on."
        ),
    )
    parser.add_argument("--base", default="origin/main", help="Base ref (default: origin/main).")
    parser.add_argument("--head", default="HEAD", help="Branch ref (default: HEAD).")
    parser.add_argument("--repo-root", default=".", help="Repository root (default: cwd).")
    args = parser.parse_args(argv)

    repo = Path(args.repo_root).resolve()

    try:
        stale = superseded_baselines(repo, args.base, args.head)
    except GitUnavailable as err:
        print(f"DID-NOT-RUN: {err}", file=sys.stderr)
        print(
            "  This guard needs the base ref present locally. In CI, fetch it "
            "(`fetch-depth: 0`) before running.",
            file=sys.stderr,
        )
        return DID_NOT_RUN

    if not stale:
        print("OK: every changed visual baseline forked from the base's current version.")
        return 0

    print("ERROR: visual baseline(s) captured from a superseded base:", file=sys.stderr)
    for path in stale:
        print(f"  {path}", file=sys.stderr)
    print(
        "\n"
        f"  `{args.base}` has changed each file above since this branch forked, so this\n"
        "  branch's capture is of an older UI. Merging it replaces the newer image\n"
        "  wholesale and reverts whatever that change fixed — silently, because the\n"
        "  regression suite compares the run against the baseline in the same tree\n"
        "  and they agree with each other.\n"
        "\n"
        "How to fix:\n"
        f"  1. Merge or rebase onto `{args.base}`, taking the BASE's version of each\n"
        "     file above. Your own capture is not worth salvaging — it was taken\n"
        "     against code you no longer have.\n"
        "  2. Re-request the capture: apply the `visual-baseline-refresh` label and\n"
        "     push (the label alone starts nothing — it is read from the PR payload\n"
        "     of the next push).\n"
        "  3. Replace the new entry's placeholder `Reason:` with a claim a reviewer\n"
        "     can check against the diff.\n",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
