#!/usr/bin/env python3
"""Guard: no Playwright visual baseline changes without recorded provenance.

Background (#611)
-----------------
Every bad VRT baseline this repo has shipped was created the same way: someone
ran ``--update-snapshots`` locally, inside a bug window, against whatever build
their dev server happened to be serving, and committed the result. The suite
then certified the bug as correct. It happened at least three times:

* ``app-header-linux.png`` kept the retired serif-"E" brand tile for ~3 months
  after ``BrandMark`` replaced it (ADR-0027/0028).
* ``admin-run-detail-v2-linux.png`` kept a page subtitle and a link style that
  the app had long since changed.
* the three mobile baselines photographed the #674 filter badge reading "2",
  and were blessed *five minutes after* the commit that fixed #674 landed —
  i.e. against a stale build.

A project-level ``maxDiffPixelRatio: 0.06`` meant none of this ever went red.
That tolerance is now gone (see ``legal-search/frontend/playwright.config.ts``),
so a wrong baseline fails loudly. This guard closes the other half: it makes a
baseline change *legible at review time* instead of arriving as an opaque blob
in a diff nobody can read.

The rule
--------
If any ``*.png`` under a guarded ``e2e/visual.spec.ts-snapshots/`` directory (see
``SNAPSHOT_DIRS``) is added, modified, or deleted relative to the merge base, then
the ``PROVENANCE.md`` **in that same directory** must also change in the same diff,
and must name every changed file.

Each surface owns its own snapshot directory and its own ledger. That is not
tidiness: a PNG has no merge strategy, so two branches that touch one surface's
layout collide on a binary file neither can merge, and a baseline parked under
another surface routes its failure to a CI job whose tree the author never opened
(#913; #902/#905 collided, #895 reported the misrouted failure).

What this can and cannot do
---------------------------
It CANNOT prove the stated reason is true, and it cannot stop a local
``--update-snapshots``. What it does is convert a silent bless into a written
claim a reviewer can check against the diff. Combined with zero tolerance (a
wrong baseline now fails CI on a clean runner) and the CI refresh job
(``visual-baseline-refresh``, which generates baselines in the same environment
that verifies them), the cheap-and-honest path is also the correct one.

Runs in CI AND pre-commit, per AGENTS.md.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# Every guarded snapshot directory. A surface that owns a visual baseline owns its
# own ledger beside it: a PNG has no merge strategy, so parking one surface's
# baselines under another's directory makes two unrelated branches collide on one
# binary file AND routes the failure to a CI job the author never touched
# (#913 — PRs #902/#905 collided; #895 reported the misrouted failure).
#
# Adding a surface here is what makes its baselines guarded. `test_every_snapshot_dir_on_disk_is_guarded`
# fails if a `visual.spec.ts-snapshots` directory exists in the tree and is not listed.
SNAPSHOT_DIRS: tuple[Path, ...] = (
    Path("legal-search/frontend/e2e/visual.spec.ts-snapshots"),
    Path("platform-control/admin/e2e/visual.spec.ts-snapshots"),
)

# Retained for readers who only care about the original surface; the guard itself
# iterates SNAPSHOT_DIRS.
SNAPSHOT_DIR = SNAPSHOT_DIRS[0]


def provenance_file(snapshot_dir: Path) -> Path:
    """The ledger that must move in the same diff as `snapshot_dir`'s baselines."""
    return snapshot_dir / "PROVENANCE.md"


PROVENANCE_FILE = provenance_file(SNAPSHOT_DIR)

# An entry must say more than the filename. These are the fields the ledger
# template asks for; a stanza missing them is a rubber stamp, not a reason.
REQUIRED_ENTRY_FIELDS = ("Generated by:", "Reason:")

# The `visual-baseline-refresh` job writes a stanza with the Reason left as a
# placeholder, because CI can record WHO regenerated a baseline and WHICH files
# moved, but only a human can say why the NEW image is correct.
#
# A `Reason:` field satisfied by that placeholder is how the mechanism goes
# decorative: three entries reached `main` with it intact (#791, #717 x2), so for
# those baselines the claim a reviewer is supposed to check was never made.
#
# Consequence, and it is deliberate: the refresh job's own commit FAILS this gate
# until someone edits the line. That is the point — the PR cannot go green on a
# machine-generated image nobody has justified. #611 exists because three bad
# baselines certified live bugs as correct for months.
#
# Substrings, not the whole sentence, so reflowing the template does not silently
# disarm this.
PLACEHOLDER_MARKERS = (
    "Replace this line with why the NEW image is correct",
    "_requested via the `visual-baseline-refresh` label._",
)


def changed_files(base_ref: str) -> list[str]:
    """Paths changed between `base_ref` and the working tree (staged + unstaged)."""
    try:
        merge_base = subprocess.run(
            ["git", "merge-base", base_ref, "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except subprocess.CalledProcessError:
        # No usable merge base (shallow clone, unknown ref). Fall back to HEAD
        # so the guard still sees uncommitted work rather than silently passing.
        merge_base = "HEAD"

    out = subprocess.run(
        ["git", "diff", "--name-only", merge_base],
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    # Include files staged/untracked but not yet in a commit.
    out += subprocess.run(
        ["git", "diff", "--name-only", "--cached"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    out += subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    return sorted({line.strip() for line in out.splitlines() if line.strip()})


def evaluate(
    changed: list[str],
    provenance_texts: str | dict[str, str],
) -> list[str]:
    """Pure core, so the self-test can drive both directions without a repo checkout.

    `provenance_texts` maps a snapshot directory (posix path) to its ledger's text.
    A bare string is accepted as shorthand for the first guarded directory, which is
    what the single-surface self-tests use.

    Returns a list of human-readable errors; empty means pass.
    """
    if isinstance(provenance_texts, str):
        provenance_texts = {SNAPSHOT_DIRS[0].as_posix(): provenance_texts}

    errors: list[str] = []
    for snapshot_dir in SNAPSHOT_DIRS:
        errors.extend(
            _evaluate_one(
                changed,
                snapshot_dir,
                provenance_texts.get(snapshot_dir.as_posix(), ""),
            )
        )
    return errors


def _evaluate_one(changed: list[str], snapshot_dir: Path, provenance_text: str) -> list[str]:
    """The original single-directory rule, applied to one guarded surface."""
    ledger = provenance_file(snapshot_dir)
    snapshot_prefix = f"{snapshot_dir.as_posix()}/"
    baselines = [
        p for p in changed if p.startswith(snapshot_prefix) and p.lower().endswith(".png")
    ]
    if not baselines:
        return []

    errors: list[str] = []

    if ledger.as_posix() not in changed:
        errors.append(
            f"{len(baselines)} visual baseline(s) changed under {snapshot_dir.as_posix()} but "
            f"{ledger.as_posix()} was not updated in the same change.\n"
            "        Every baseline in this repo that certified a bug was a silent "
            "local re-bless (#611).\n"
            "        Record what you regenerated and why."
        )

    for path in baselines:
        name = Path(path).name
        if name not in provenance_text:
            errors.append(f"baseline '{name}' changed but is not named in {ledger.as_posix()}.")

    # The newest stanza must carry real fields, not just a filename list.
    newest = _newest_entry(provenance_text)
    if newest is not None:
        missing = [f for f in REQUIRED_ENTRY_FIELDS if f not in newest]
        if missing:
            errors.append(
                f"the most recent {ledger.as_posix()} entry is missing required "
                f"field(s): {', '.join(missing)}"
            )

        left_over = [marker for marker in PLACEHOLDER_MARKERS if marker in newest]
        if left_over:
            errors.append(
                f"the most recent {ledger.as_posix()} entry still carries the refresh job's "
                "placeholder reason.\n"
                "        CI can record who regenerated a baseline and which files moved; "
                "only you can say why\n"
                "        the NEW image is correct. Replace the `Reason:` line with a claim "
                "a reviewer can\n"
                "        check against the diff — what changed in the UI, and what must "
                "NOT have changed."
            )

    return errors


# Entry headings are date-anchored (`## 2026-07-19 — …`). Matching on a bare
# `## ` instead would treat the file's own prose headings as entries — the
# self-test caught exactly that.
ENTRY_HEADING = re.compile(r"^## (\d{4}-\d{2}-\d{2})\b", re.MULTILINE)


def _newest_entry(provenance_text: str) -> str | None:
    """The first date-headed stanza — entries are prepended newest-first."""
    matches = list(ENTRY_HEADING.finditer(provenance_text))
    if not matches:
        return None
    start = matches[0].start()
    end = matches[1].start() if len(matches) > 1 else len(provenance_text)
    return provenance_text[start:end]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-ref",
        default="origin/main",
        help="Ref to diff against (default: origin/main).",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    provenance_texts = {}
    for snapshot_dir in SNAPSHOT_DIRS:
        path = repo_root / provenance_file(snapshot_dir)
        provenance_texts[snapshot_dir.as_posix()] = (
            path.read_text(encoding="utf-8") if path.exists() else ""
        )

    errors = evaluate(changed_files(args.base_ref), provenance_texts)
    if errors:
        print("FAIL: visual baseline provenance", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        print(
            "\nHow to fix:\n"
            "  Preferred — let CI generate the baselines in the same environment that\n"
            "  verifies them: add the `visual-baseline-refresh` label to your PR. The\n"
            "  job regenerates the baselines on the CI runner and writes the\n"
            "  PROVENANCE.md entry for you.\n\n"
            "  Otherwise — add an entry to the PROVENANCE.md beside the baseline\n"
            "  (each surface owns its own ledger) naming each regenerated file, how it was\n"
            "  generated, and why the NEW image is correct. 'Tests were red' is not a\n"
            "  reason; that is the failure mode this guard exists to catch (#611).",
            file=sys.stderr,
        )
        return 1

    print("OK: visual baseline provenance")
    return 0


if __name__ == "__main__":
    sys.exit(main())
