steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - ${_DOCKERFILE}
      - -t
      - ${_IMAGE}
      - ${_CONTEXT}
images:
  - ${_IMAGE}
