/**
 * Pixel baselines for the admin run-detail v2 layout.
 *
 * WHY THIS FILE IS HERE AND NOT IN `legal-search/frontend/e2e/` (#913)
 * --------------------------------------------------------------------
 * This capture used to live in `legal-search/frontend/e2e/visual.spec.ts`, with its
 * baseline PNG committed under that surface's `visual.spec.ts-snapshots/`. Two costs,
 * both measured:
 *
 * 1. A PNG has no merge strategy. Any two branches that touch admin layout collide on
 *    one binary file and cannot be merged — PRs #902 and #905 hit exactly that.
 * 2. An admin change broke a *legal-search* CI job, which is undiscoverable from the
 *    admin tree (#895). The failing job named a surface the author had not touched.
 *
 * The capture is unchanged in intent: the "Run overview" decision quadrant (the
 * `Why this matters` primary card plus its three subordinate cards) and the collapsed
 * lifecycle accordion stack below it. `RunShowV2` renders no layout that any Vitest
 * layer can see — jsdom has no layout engine and applies no stylesheet — so this is
 * the only guard on that quadrant's geometry.
 *
 * ZERO PIXEL TOLERANCE. `playwright.config.ts` sets no `maxDiffPixelRatio`, which
 * means Playwright's default: zero differing pixels. Do not add a project-level
 * tolerance. On a 1600x900 full-page shot a 6% ratio is ~86k pixels of licensed
 * drift, which is how the legal-search suite stayed green across a ~260px mislaid
 * filter rail for 3.5 months (#605/#611). If one snapshot genuinely needs slack,
 * scope it to that one `toHaveScreenshot` call with a written justification.
 *
 * Baselines are generated by the `admin-visual-baseline-refresh` CI job (add the
 * `visual-baseline-refresh` label to the PR, then push) so generation and
 * verification share an environment — see `visual.spec.ts-snapshots/PROVENANCE.md`.
 *
 * Every request is mocked with `page.route`, as every spec in this directory does.
 * No backend, no database.
 *
 * Selection: tagged `@visual` so `npm run e2e` (which runs `--grep-invert @visual`)
 * leaves it to the dedicated `npm run e2e:visual` job. Both are invoked by
 * `.github/workflows/platform-control.yml`, which is what
 * `scripts/check-e2e-spec-coverage.sh` asserts.
 */

import type { Page, Route } from "@playwright/test";
import { DECISION_SUPPORT } from "./fixtures/pipelineHealth";
import { expect, test } from "./support/test";

const RUN_ID = "run_01";

const RUN = {
  run_id: RUN_ID,
  source_id: "src_01",
  source_version_id: "sv_01",
  source_name: "Swiss Federal Court",
  version_label: "2026.04.06",
  mode: "production",
  status: "running",
  started_at: "2026-04-06T10:00:00Z",
  completed_at: null,
  artifacts_count: 3,
  captured_resources_count: 3,
  failure_reason: null,
  created_at: "2026-04-06T10:00:00Z",
  updated_at: "2026-04-06T10:02:00Z",
};

/**
 * Four stages in four distinct states. A baseline over a single state cannot show a
 * regression in how the other three are drawn, and the stage row is the densest part
 * of this layout.
 *
 * `decision_support` is spread from the shared fixture rather than pasted: #908 moved
 * those five answers server-side, so a spec that hand-maintains its own copy mocks a
 * response shape the API may no longer return.
 */
const PIPELINE_HEALTH = {
  run_id: RUN_ID,
  source_id: "src_01",
  source_version_id: "sv_01",
  mode: "production",
  run_status: "running",
  overall_status: "in_progress",
  stages: [
    {
      stage: "acquisition",
      status: "ok",
      detail: "Acquisition completed successfully.",
      updated_at: "2026-04-06T10:01:00Z",
    },
    {
      stage: "document_intelligence",
      status: "in_progress",
      detail: "DI ingestion is processing pages.",
      updated_at: "2026-04-06T10:02:00Z",
    },
    {
      stage: "projection",
      status: "pending",
      detail: "Projection awaits DI completion.",
      updated_at: null,
    },
    {
      stage: "search",
      status: "pending",
      detail: "Search publish waits for projection updates.",
      updated_at: null,
    },
  ],
  processing_status_event_count: 2,
  document_lifecycle_event_count: 1,
  decision_support: {
    ...DECISION_SUPPORT,
    why_it_matters: {
      code: "production_run",
      text: "This production run determines whether the source version can safely flow into the live operator surface.",
    },
    what_is_blocked: {
      code: "moving_no_block",
      text: "No stage is blocked, but the pipeline is still moving and may need operator attention soon.",
    },
    what_changed_recently: {
      code: "latest_stage_update",
      text: "Most recent stage update: document intelligence is in progress.",
    },
  },
};

const EMPTY_PAGE = { data: [], total: 0, limit: 100, offset: 0 };

async function mockRunDetail(page: Page) {
  // Benign catch-all first (lowest priority), so any read model not named below
  // resolves to an empty 200 rather than hanging — an in-flight request leaves a
  // spinner in the frame, and a spinner in a pixel baseline is nondeterminism.
  await page.route("**/api/platform-control/**", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(EMPTY_PAGE),
    }),
  );

  const json = (body: unknown) => (route: Route) =>
    route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(body) });

  await page.route(`**/v1/runs/${RUN_ID}/pipeline-health`, json(PIPELINE_HEALTH));
  await page.route(`**/v1/runs/${RUN_ID}`, json(RUN));
}

test.describe("Visual regressions @visual", () => {
  test("run detail v2 — primary decision hierarchy matches baseline", async ({ page }) => {
    // Next `dev` compiles routes lazily on first request, and admin's shared
    // `@evidara/ui` tree makes that first cold compile expensive (PR #503). Give the
    // first navigation headroom so a one-time compile is not read as a layout bug.
    test.setTimeout(120_000);

    await page.addInitScript(() => {
      window.localStorage.setItem("evidara_user_role", "admin");
    });
    await mockRunDetail(page);
    await page.setViewportSize({ width: 1600, height: 900 });

    await page.goto(`/#/runs/${RUN_ID}/show`, { waitUntil: "load", timeout: 90_000 });

    // `exact: true` matters here. Playwright's `name` is a SUBSTRING match by
    // default, and `PipelineHealthBanner` renders a second heading further down the
    // page — "Pipeline decision support". A non-exact locator resolves to both, and
    // the `toHaveCount(1)` below then asserts nothing about the quadrant it names.
    const decisionSupport = page.getByRole("heading", { name: "Decision support", exact: true });
    await expect(decisionSupport).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole("heading", { name: new RegExp(`Run ${RUN_ID}`) })).toBeVisible({
      timeout: 20_000,
    });
    // `RunDetailSectionsV2` renders collapsed accordion items below the metadata
    // grid. Waiting for the last of them means the capture includes the full
    // lifecycle stack rather than racing a half-rendered page.
    await expect(page.getByRole("button", { name: /Provider Jobs/ })).toBeVisible({
      timeout: 20_000,
    });

    // Anti-duplicate assertion. Pixel tolerance is zero here, but a *structural*
    // regression like a double-mounted quadrant can still produce a stable image;
    // this DOM-level check cannot be satisfied by one.
    await expect(decisionSupport).toHaveCount(1);

    await expect(page).toHaveScreenshot("run-detail-v2.png", { fullPage: true });
  });
});
