"""Render dbt source YAML for the published document-intelligence surfaces.

The column list attached to every published source is generated from the
canonical ``PublishedSurfaceDefinition`` records in
``document_intelligence.persist.surfaces``. A source-level
``dbt_expectations.expect_table_columns_to_match_set`` test fails loudly when
the runtime starts writing a column that is not declared in the contract, or
stops writing one the contract promises. The generated YAML is checked into
``dbt/models/sources_published.generated.yml`` and a unit test keeps the file
in sync with the surface definitions.
"""

import argparse

from document_intelligence.persist.surfaces import iter_surface_definitions

_HEADER = (
    "# AUTO-GENERATED by document_intelligence.bootstrap.render_source_contracts.\n"
    "# Source of truth: src/document_intelligence/persist/surfaces.py\n"
    "# Regenerate with: document_intelligence_render_source_contracts \\\n"
    "#   > dbt/models/sources_published.generated.yml\n"
    "# A unit test fails if this file drifts from the surface definitions.\n"
)


def render_published_sources_yaml(
    *,
    source_name: str = "published",
    schema_name: str = "published",
    env_var_name: str = "DATABRICKS_CATALOG",
    default_catalog: str = "evidara_document_intelligence_dev",
) -> str:
    lines: list[str] = [_HEADER, "version: 2", "", "sources:", f"  - name: {source_name}"]
    lines.append(f"    database: \"{{{{ env_var('{env_var_name}', '{default_catalog}') }}}}\"")
    lines.append(f"    schema: {schema_name}")
    lines.append("    tables:")

    for definition in iter_surface_definitions():
        lines.append(f"      - name: {definition.surface_name}")
        lines.append(f'        description: "{definition.description}"')
        lines.append("        tests:")
        lines.append("          - dbt_expectations.expect_table_columns_to_match_set:")
        lines.append("              column_list:")
        for column in definition.columns:
            lines.append(f"                - {column.name}")
        lines.append("        columns:")
        for column in definition.columns:
            lines.append(f"          - name: {column.name}")
            lines.append(f'            description: "{column.description}"')
            if not column.nullable:
                lines.append("            tests:")
                lines.append("              - not_null")

    return "\n".join(lines) + "\n"


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="document_intelligence_render_source_contracts",
        description=(
            "Render dbt source YAML for document-intelligence published surfaces, "
            "including a dbt_expectations column-set contract test."
        ),
    )
    parser.add_argument("--source-name", default="published")
    parser.add_argument("--schema-name", default="published")
    parser.add_argument("--env-var-name", default="DATABRICKS_CATALOG")
    parser.add_argument("--default-catalog", default="evidara_document_intelligence_dev")
    args = parser.parse_args(argv)

    print(
        render_published_sources_yaml(
            source_name=args.source_name,
            schema_name=args.schema_name,
            env_var_name=args.env_var_name,
            default_catalog=args.default_catalog,
        ),
        end="",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(cli())
